name: runners workflow
on: workflow_dispatch

jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
  - name: info of os
    run: cat /etc/os-release
  - name: installed softwares
    run: java --version
     

 job2:
  runs-on: ubuntu-22.04
  steps: 
  - name: info os
    run: cat /etc/os-release
